### ISSUE TITLE
how do I find the values of a sensor (i.e. battery)

### ISSUE THREAD

**Issue by emjayking** [amymcgovern/pyparrot#106]
Hi I'm new to python (sorry)
I was wondering how I find the current battery value of my mambo (BLE) drone. I have read the documentation however it makes little to no sense to me

**Comment by mromanelli** [comment]
Hi, emjayking.
You can access drone's sensors using the attribute called "sensors". For example:
```
...
mambo = Mambo(mamboAddr, use_wifi=True)
print("trying to connect to mambo now")
success = mambo.connect(num_retries=3)
print("connected: %s" % success)

if (success):
    # get the state information
    print("sleeping")
    mambo.smart_sleep(1)
    mambo.ask_for_state_update()
    mambo.smart_sleep(1)
    ...
    print("Battery level: %d", mambo.sensors.battery)
    ....
```
Remember to call the function `ask_for_state_update()`; from the docs: "This really only needs to be called once at the start of the program to initialize some of the state variables".
