### ISSUE TITLE
Could not find some sensor : Bebop2

### ISSUE THREAD

**Issue by tomoyuki1111** [amymcgovern/pyparrot#11]
I am looking for python code for bebop2, and I find your source, thank you. 
I tried "demoBebopIndoors.py", but video streaming doesn't work and these comment appears:
  _"Could not find sensor in list -ignoring for now. Packet infobelow "_
  _(142,  0, 3)_
The header_tuple=(134, 0, 3), (134, 0, 4),(144, 0, 2), (144, 0,1) are also appeared, 
and one Error comment "_Error:tried to parse a bad sensor packet_"
I don't know the cause, but sensor_name is none maybe.
However, other commands such as takeoff and land works.

**Comment by amymcgovern** [comment]
This is not a bug.  This is reporting a sensor that I am not currently parsing.  I know about it.  it isn't an important sensor which is why I put it as a lower priority item to get to.

**Comment by tomoyuki1111** [comment]
Thank you for your kind replay. I understand it.
To erase these comments appropriately, I will try to add some code for the other xml file data to project_xml.
