### ISSUE TITLE
self.groundcam only defined if use_wifi is True - causing errors in .disconnect() (Class Minidrone)

### ISSUE THREAD

**Issue by Tzarls** [amymcgovern/pyparrot#115]
Hi. I think there´s an error around line 324 in file Minidrone.py, class Minidrone. If Wifi is enabled then self.groundcam is initialized, but if you are only using BLE then it is never initialized. This causes an error in line 738 when calling disconnect() (Class Mambo) because self.groundcam doesn´t exist.

[https://github.com/amymcgovern/pyparrot/blob/a921301c74f6f0a3432ae96e40418ae50daf4474/pyparrot/Minidrone.py#L324](url)

[https://github.com/amymcgovern/pyparrot/blob/a921301c74f6f0a3432ae96e40418ae50daf4474/pyparrot/Minidrone.py#L738](url)

**Comment by amymcgovern** [comment]
Oh, good catch!  I had to adjust the ground cam when they broke the ftp server on their latest firmware and I didn't test BLE, only wifi.  I'll fix that right now.

**Comment by amymcgovern** [comment]
should be fixed now.
