### ISSUE TITLE
macos support

### ISSUE THREAD

**Issue by vvo** [amymcgovern/pyparrot#12]
Hey hi, in the README it seems you only support Linux. Do you have any plans on supporting macos? Thanks!

**Comment by amymcgovern** [comment]
The bluetooth support is Linux only but the wifi interface works on any OS including Mac.  I develop on the Mac.

**Comment by vvo** [comment]
Ok thanks I have a parrot mambo (BLE, no FPV) so I will pass this time.

Nice API BTW, super simple

**Comment by vvo** [comment]
Ok thanks I have a parrot mambo (BLE, no FPV) so I will pass this time.

Nice API BTW, super simple
