### ISSUE TITLE
Can't takeoff

### ISSUE THREAD

**Issue by aleixpb2** [amymcgovern/pyparrot#120]
I ran demoMamboTricks.py connecting to the drone using BLE with Ubuntu, but it doesn't take off. This is the output:

```
OpenCVAvailable is False
trying to connect
 trying to connect to the minidrone at address [my address] 
 connected!  Asking for services and characteristics 
 magic handshake to make the drone listen to our commandsandsensors 
 initializing notification delegate 
connected: True
sleeping
 Could not find sensor in list - ignoring for now.  Packet info below. 
(2, 25, 3)
 Could not find sensor in list - ignoring for now.  Packet info below. 
(2, 25, 5)
taking off!
flying state is landed
Flying direct: going up
flip left
flying state is landed
mambo flip result True
flip right
flying state is landed
mambo flip result True
flip front
flying state is landed
mambo flip result True
flip back
flying state is landed
mambo flip result True
landing
flying state is landed
disconnect
```

The takeoff function returns true (see my pull request), so the commands are sent successfully but not executed for some reason. Do you have any idea on the cause?

Thanks,
Aleix

**Comment by amymcgovern** [comment]
what firmware are you running?  I haven't used the BLE in a long while since all of mine have wifi.  It could be something has changed in the new firmware (lots of things changed in the latest one).

**Comment by aleixpb2** [comment]
Thanks for your suggestion. I updated the firmware and now it works perfectly
