### ISSUE TITLE
Does Mambo drone send the 'Flying' Piloting State?

### ISSUE THREAD

**Issue by anoop4** [amymcgovern/pyparrot#128]
I see that the Parrot mambo drone sends all the different piloting state except for the 'Flying' state.

We have to currently reply on smart_sleep() to prevent sequential fly_direct() commands from being skipped.

I was wondering if the PilotingState change from 'hovering' to 'flying' can be used as an indication of a previous move complete. This can help in avoiding the samrt_sleep() commands in the pyparrot examples.

Unfortunately, I don't see the 'Flying' state sent by the drone with the latest 3.0.26 FW.

Any thoughts?

**Comment by amymcgovern** [comment]
are you using wifi or BLE?

**Comment by anoop4** [comment]
Wifi

**Comment by amymcgovern** [comment]
windows?  I've seen an issue with windows sensors specifically:

https://pyparrot.readthedocs.io/en/latest/faq.html#i-m-using-windows-and-my-drone-gives-me-lots-of-timeout-errors

**Comment by anoop4** [comment]
Yes I am seeing this in my windows system. Will get back to you after checking in my Mac system.

**Comment by anoop4** [comment]
I am getting the same behavior in my mac system as well. The drone doesn't seem to send the 'Flying' state at all. 

I get other states such as taking off, hovering, landing, landed, initializing, and emergency
