### ISSUE TITLE
I'am wondering how to turn the bebop2?

### ISSUE THREAD

**Issue by lengyuyu2333** [amymcgovern/pyparrot#130]
File "fly.py", line 21, in <module>
    bebop.turn_degrees(45)
AttributeError: 'Bebop' object has no attribute 'turn_degrees'

This fonction is not used like this? Hoping for help :)

**Comment by amymcgovern** [comment]
There is not a turn_degrees function in the bebop.  That is an error in the documentation and I will fix it right now.  There is a move_relative and that will accomplish what you want.  For some reason, mambo has an internal turn_degrees function while bebop does everything in radians (and uses a different command).
