### ISSUE TITLE
Failed to convert image for snapshot

### ISSUE THREAD

**Issue by cannguyen275** [amymcgovern/pyparrot#133]
I try to save image of bebop 2 in my PC with NVidia gpu 1080 Tx . But error like this : 
[000056425b61a7e8] vdpau_chroma filter error: corrupt VDPAU video surface 0x7f6fc00866f0

Can you help  me fix it. Thanks

**Comment by amymcgovern** [comment]
that's inside your image converter.  Not inside my code.
