### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by m3m3-chan** [amymcgovern/pyparrot#134]
Hello! 
I am a total newbie in all this drone/ python so excuse me if my question is very basic.
 I installed  your project (via "git clone" ) and all required software for the pyparrot in my conda py2.7 environment but when I want to import the pyparrot it says module not found! How can I fix this?
thanks,

**Comment by revanth7667** [comment]
hi,
please specify your operating system
pyparrot works on python 3 and not on python 2. so use pip3 instead of pip to install the required modules

**Comment by amymcgovern** [comment]
https://pyparrot.readthedocs.io/en/latest/installation.html

**Comment by m3m3-chan** [comment]
managed to install successfully
thanks!
