### ISSUE TITLE
decrease/eliminate video latency 

### ISSUE THREAD

**Issue by m3m3-chan** [amymcgovern/pyparrot#140]
Hello, 
is there any way to decrease the latency in the video stream? I found out when applying ML modules on top of the video there is a huge lag.
I was wondering if there's any trick to at least minimize the lagging of the original streaming? I know @mmaz suggested g-streamer  but I am running Windows machine and found it difficult to follow his method.
thanks,

**Comment by malfonso0** [comment]
hi. see this
https://github.com/amymcgovern/pyparrot/issues/102#issuecomment-487587094

**Comment by m3m3-chan** [comment]
will try it out, thanks!
