### ISSUE TITLE
NameError: no function 'libvlc_new'

### ISSUE THREAD

**Issue by YM-P51** [amymcgovern/pyparrot#149]
Help !
It raises this error "NameError: no function 'libvlc_new'  ". But there is the 'libvlc_new' function. Why?

**Comment by YM-P51** [comment]
when run this file "demoBebopVersionGUI.py"

**Comment by amymcgovern** [comment]
Do you have your paths setup right?  Sounds like a python path issue to me.

**Comment by YM-P51** [comment]
I don't know...
This error occurred, when calling function 'bebopVision.open_video()'.

**Comment by amymcgovern** [comment]
What OS?

**Comment by YM-P51** [comment]
ubuntu 16.04

**Comment by amymcgovern** [comment]
Ok.  This is odd.  Can you check your python paths?  It really should be seeing it.

**Comment by YM-P51** [comment]
ok ,I will check it again
Thank you

**Comment by cheloveg** [comment]
Maybe you didn't have VLC(app itself, not library) installed, that was my problem
