### ISSUE TITLE
parrot mambo error (canot import "service browser from zeroconf)

### ISSUE THREAD

**Issue by rhj0970** [amymcgovern/pyparrot#177]
Hi! I was trying to install pyparrot on Rasberry Pi 3 to operate mambo and I finished through the installation guide and when I try to run sample code it gives me an error saying it can't find import service browser from zeroconf. I set up to mambo bluetooth address and set WIFI to false. Also I changed "From pyparrot.mambo to pyparrot.Minidrone since it doesn't have mambo class files.

**Comment by amymcgovern** [comment]
Sorry this got lost in my inbox.  we definitely are not using Pyparrot.mambo anymore.  Only Minidrone.  Where is that sample code and I'll fix it.  Also, you shouldn't need zeroconf since that is wifi only.

**Comment by rhj0970** [comment]
I was running this code through the python installed in rasberry pi instead of command line.
I got it working now
