### ISSUE TITLE
Computer vision on Parrot drone using pyparrot

### ISSUE THREAD

**Issue by viet2411** [amymcgovern/pyparrot#212]
Hello,
I've used DJI Tello drone for my deep learning + computer vision project before, but it had some limitations and now I'm looking for a better drone. 
I'm considering buying a Parrot drone, and I want to use Python + OpenCV libraries on Windows/Linux.

Is pyparrot suitable for the above requirements? Because it seems like some people had troubles with opencv using pyparrot.
And what Parrot drone (Mambo FPV, Bebop 2 or ANAFI) is suitable for my project? Can anyone give me some suggestion?

Thank you and best regards.

**Comment by amymcgovern** [comment]
Open CV works fine minus that one bug that I documented well.  I have not been supporting the library lately due to other duties and parrot no longer selling a lot of the drones I was using.  My battery charger for the Bebop 2 died and I now have 2 bebop 2s that won't even fly :(

**Comment by viet2411** [comment]
Thank you for your quick reply.

Looking forward to hearing from your updates soon.
