### ISSUE TITLE
Accelerometer

### ISSUE THREAD

**Issue by edmondja** [amymcgovern/pyparrot#23]
Hello, is there a way to gather accelerometers' information via the API ??

**Comment by amymcgovern** [comment]
Mambo or Bebop?  Everything that is sent is stored.  The Mambo doesn't send that.  The bebop may?  I literally store everything sent in a dictionary for the bebop.

**Comment by edmondja** [comment]
I meant the mambo. How do I know if the drone hits a wall ? I only have the camera for that ??

**Comment by amymcgovern** [comment]
Unfortunately, yes.  I agree on needing the accelerometer.  I'd suggest that you post on the parrot development board and see if they have a way to get that information!

**Comment by edmondja** [comment]
Technically they do, since the research paper uses an AR drone 2.0 from Parrot aswell..

**Comment by amymcgovern** [comment]
As I have said, the information is inside the mambo.  You just need a way to get it out.  Post on the developer board!  I am not a parrot employee.  I don't know the internals.  Just a developer from the outside.

**Comment by amymcgovern** [comment]
Also, the AR uses an entirely different SDK.  I have used it and I had access to a lot more sensors.  I have not found nearly as much information about how to get the data from the mambo.

**Comment by edmondja** [comment]
Sad : 
http://forum.developer.parrot.com/t/mambo-accelerometer/7239/2
Thank you.

**Comment by amymcgovern** [comment]
Sad but not surprising.  Sorry!
