### ISSUE TITLE
ImportError: No module named 'utils.colorPrint'

### ISSUE THREAD

**Issue by Tenshiiiii** [amymcgovern/pyparrot#26]
First of all, i found the error that says "ImportError: No module named 'utils".
So, i used the command "sudo pip install utils" and passed this error, but now I found another error says "ImportError: No module named 'utils.colorPrint'" and i can't solve it.
Please help me

**Comment by amymcgovern** [comment]
Python paths.  utils is in this code.  Pip can't do that for you.  Be sure you are in the right directory when you run the demos

**Comment by mulysatest** [comment]
I solved her problem by run the command to the proper path, now everything work. THis issues can be closed now. THank you
