### ISSUE TITLE
How to tell pyParrot to use specific BLE device ?

### ISSUE THREAD

**Issue by mulysatest** [amymcgovern/pyparrot#31]
I got two BLE: 1. Build-in BLE 4.0 ,   2. Dongle BLE 4.0 USB.
Everything working fine with Dongle BLE 4.0 USB. 
How I can enforce PyParrot to use build-in BLE 4.0 that came with the RaspberryPi/ Asus TinkerBoard? 
Right now if I remove the Dongle BLE 4.0 USB the code will not working any more.

Pls kindly advice how to tell pyParrot to use internal one. 

Thank you

**Comment by amymcgovern** [comment]
It should be using whatever pybluez is using.  So this is a question for that package rather than me.
