### ISSUE TITLE
Emergency landing?

### ISSUE THREAD

**Issue by mulysatest** [amymcgovern/pyparrot#32]
In case of emergency that Mambo would crash in to something, how to emergency stop the drone ?

**Comment by amymcgovern** [comment]
There is an emergency and safe emergency command.  You can send those.  It turns off all motors immediately so it will fall out of the sky...

**Comment by mulysatest** [comment]
As I knew the Mambo drone will behave according to python command that executed line by line. 
So, it mean that it will try to finish the current line of code first before next line. 
If it behave like this how we can inject the emergency command suddenly during the processing of the current command that I would like to abort?

Do you have example code?

**Comment by amymcgovern** [comment]
Although it is not documented yet for the next official release, there is an example in DroneVisionGUI and demoMamboVisionGUI where you have multi-threading and a GUI and buttons to land.  In the case of the mambo and your desired emergency command, you should change the land command to an emergency command.

**Comment by Vabe7** [comment]
Another solution would be to pack everything in a try, except construct like [here:](https://stackoverflow.com/questions/21120947/catching-keyboardinterrupt-in-python-during-program-shutdown)
Then a KeyboardInterupt would do whatever you like. I think I will add that to all my codes, since I can test and the drone lands automatically if I have to kill the program.

**Comment by amymcgovern** [comment]
That's a good answer!

**Comment by r3dh0t** [comment]
We did a similar thing Vabe... Although we wrapped the entire program in a Try and had two Excepts: one for keyboard interrupt and one that captures any exception.

This prevent the drone from flying with errenous code (which results in the drone hovering indefinitely).
