### ISSUE TITLE
bebopVision.open_video() is not succeed

### ISSUE THREAD

**Issue by taniguchi-t-nmri** [amymcgovern/pyparrot#36]
Hello.
I tried to run "demoBebopVision.py", and the drone connection was OK, but "bebopVision.open_video()" was not succeed.
This problem is similar to the closed Issues "Problem with Vision #15", however no solutions are shown in that Issues.

And ,the error comment are follows:

Opening ffmpeg
ffmpeg -protocol_whitelist "file,rtp,udp" -i C:\Users\Tomoyuki\Desktop\Bebop2\pyparrot-master\utils/bebop.sdp -r 30 image_%03d.png &
starting vision thread
Opening non-blocking readers
timeout - trying again
ffmpeg version N-90054-g474194a8d0 Copyright (c) 2000-2018 the FFmpeg developers

  built with gcc 7.2.0 (GCC)

  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libmfx --enable-amf --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth

  libavutil      56.  7.101 / 56.  7.101

  libavcodec     58. 11.101 / 58. 11.101

  libavformat    58.  9.100 / 58.  9.100

  libavdevice    58.  1.100 / 58.  1.100

  libavfilter     7. 12.100 /  7. 12.100

  libswscale      5.  0.101 /  5.  0.101

  libswresample   3.  0.101 /  3.  0.101

  libpostproc    55.  0.100 / 55.  0.100

[udp @ 000001d7fc73ec40] 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)

[udp @ 000001d7fc74f540] 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)

timeout - trying again
timeout - trying again
[sdp @ 000001d7fc72a880] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size

Consider increasing the value for the 'analyzeduration' and 'probesize' options

Input #0, sdp, from 'C:\Users\Tomoyuki\Desktop\Bebop2\pyparrot-master\utils/bebop.sdp':

  Duration: N/A, bitrate: N/A

    Stream #0:0: Video: h264, none, 90k tbr, 90k tbn, 180k tbc

Output #0, image2, to 'image_%03d.png':

Output file #0 does not contain any stream

Having trouble connecting to the camera 1.  A reboot of the mambo may help.

**Comment by amymcgovern** [comment]
Have you tried it repeatedly? Because I have found the camera to sometimes get in a funny state and simply rebooting makes it all work again.

**Comment by tomoyuki1111** [comment]
Thank you for your advice. I tried it repeatedly, and the pictures in images folder was created sometimes (This means failing occasionally ).
I don’t know why it works and it does not work. Is this problem inevitable?

**Comment by amymcgovern** [comment]
I have found the bebop to be extremely reliable in its vision.  Far more so than the mambo, in fact.  So I am very surprised.  You are using a bebop 2?

**Comment by tomoyuki1111** [comment]
Yes, I use bebop2 and it's firmware version is 4.4.0. 
Many following messages appears, and pictures in images folder was written sometimes. 
In some cases, a part of the photo is missing. Perhaps it is my wifi environment problem.

[h264 @ 0x55725681e760] SPS unavailable in decode_picture_timing
[h264 @ 0x55725681e760] non-existing PPS 0 referenced

**Comment by amymcgovern** [comment]
Those kinds of errors that you are mentioning I do see.  I do agree it could be your wifi connection!
