### ISSUE TITLE
How to change streaming resolution of parrot mambo fpv?

### ISSUE THREAD

**Issue by hina3271** [amymcgovern/pyparrot#38]
The default streaming resolution of mambo is 360p.
I want to change this to 720p.
I tried it by this code but this did not work. :(
I define this function in Mambo class in Mambo.py

def SetResolution(self)
(command_tuple, enum_tuple) = self.command_parser.get_command_tuple_with_enum("minidrone", +"VideoSettings", "VideoResolution", "hd")
return self.drone_connection.send_enum_command_packet_ack(command_tuple, enum_tuple)

I used SetResolution function in demoMamboVision.py
after the function called 'success = mambo.connect(num_retries=3)'
How should I modify the code to change resolution?
Thank you

**Comment by amymcgovern** [comment]
I haven't tried to change that.  I can look into it shortly.

**Comment by freaad** [comment]
did you success to change the resolution?
I read the arsdk3 and I think that there are only 2 option 720p or 360p for bebop2.

**Comment by srijith-vijay** [comment]
The above-mentioned command tuple was able to successfully change the video resolution. I verified this by executing the above command while VLC was playing the video stream

**Comment by hina3271** [comment]
You mean SetResolution function works well?

**Comment by srijith-vijay** [comment]
That's right. The command tuple you are using is the one I used. But I was sending the tuple after the initialization, not immediately after the connect.

**Comment by amymcgovern** [comment]
Excellent!  I'll get it added.  I just hadn't had a chance to test it yet.
