### ISSUE TITLE
No image appears on the VLC. (demoBebopVisionGUI.py)

### ISSUE THREAD

**Issue by tomoyuki1111** [amymcgovern/pyparrot#41]
I am sorry to frequently ask you a question.
I also tried to run demoBebopVisionGUI.py, and it successfully connected.
PyQt GUI appears and "Run my program" button is pushed, but there are no images on the VLC(Version 3.0.1), and there are no error codes.
I tried it and reboot  repeatedly, but no images appears. Of course, the camera cap is removed.
Please tell me the way to get the real time images correctly.

**Comment by amymcgovern** [comment]
I assume you have VLC correctly installed?

**Comment by freaad** [comment]
pip install python-vlc 
is required.

**Comment by amymcgovern** [comment]
No.  You need the program VLC.  https://www.videolan.org/vlc/index.html

**Comment by amymcgovern** [comment]
It actually installs something different than python-vlc.  That is the library.  The program is required also.

**Comment by freaad** [comment]
Yes I installed both.

**Comment by tomoyuki1111** [comment]
I had installed VLC from same URL you show. I don't install python-vlc.
In addition, I tried to run the sample (https://github.com/devos50/vlc-pyqt5-example) you wrote in "DroneVisionGUI.py", and It's succeeded. Maybe, VLC is installed correctly.

**Comment by tomoyuki1111** [comment]
Hello
I would like to report you the success of demoBebopVisionGUI of newest pyparrot.
I don’t know the causes, but thank you very much.
I tried this in apartment with many wifi condition, and perhaps this was bad.
