### ISSUE TITLE
Problems sending commands to Mambo after updating to 3.0.17

### ISSUE THREAD

**Issue by davismariotti** [amymcgovern/pyparrot#48]
Recently the smartphone app forced me to update to 3.0.17, and since then, I've been getting odd errors relating to sensors:
` Could not find sensor in list - ignoring for now.  Packet info below. 
(2, 25, 3)
 Could not find sensor in list - ignoring for now.  Packet info below. 
(2, 25, 5)`
I've also had a harder time connecting to the camera (I'm using opencv directly to connect to the rtsp feed. It now tends to stop reading frames after about 10 frames. Minutes before the update I was able to read at least 1000 frames without issue.

Has anything changed in this firmware update that you know of?

I've tried running the sample program: demoMamboDirectFlight.py

When I do, it tends to combine some of the commands, for example sending a vertical movement command followed by a turn+forward command will result in a climbing turn.

My source is available here: https://github.com/davismariotti/JordanAIDrone/blob/master/drone.py

**Comment by amymcgovern** [comment]
The RTSP stream has never been reliable for me in opencv.  There are a LOT of people on the net who talk about the same issues for RTSP and opencv so I made two work arounds.  DroneVision uses ffmpeg to do the vision and DroneVisionGUI uses liblvc.
