### ISSUE TITLE
No sensordata when script is executed in command line

### ISSUE THREAD

**Issue by CedricMingneau** [amymcgovern/pyparrot#52]
I have a rather bizarre problem when running some of my scripts (which use the pyparrot package). Whenever I run them in PyCharm, "udp_receive_sock" receives data from the drone and sensors_dict (from Bebop) gets filled up and updates nicely. However, when I run the same script in Powershell, no data gets sent back from the drone. What's striking, is that all commands like "safe_takeoff" or "fly_direct" _do work_.

In the screenshot below I've framed the problem.

![data not coming in](https://user-images.githubusercontent.com/29070207/40739975-d4bd2314-6447-11e8-8ce0-73ebe5810eef.png)

As can been seen, "udp_receive_sock" continuously times out. "batterij" is dutch for battery, and should normally display the current battery percentage.
Have I perhaps called the script in a wrong way?
I've also tried to run it like this:

![alternative command](https://user-images.githubusercontent.com/29070207/40740174-66184e4c-6448-11e8-89f4-c64092b199be.png)

This gave the same effect...

Any help would be appreciated, thanks!

**Comment by amymcgovern** [comment]
That is really odd!  I usually use pycharm when I am coding and running but I have certainly run from the command line before.  It seems like there is something stopping the connection and sockets.  Could there be permissions issue?  I see you are running in windows so I wonder if somehow the shell is not getting full access to permissions?

**Comment by CedricMingneau** [comment]
Of course! I should've known the problem was caused by Windows Firewall. You have to disable Windows Defender Firewall for public networks. After that everything works. Thanks for the help Amy!
