### ISSUE TITLE
Does this work with the Parrot Rolling Spider?

### ISSUE THREAD

**Issue by petercunha** [amymcgovern/pyparrot#60]
**_Update_: The Rolling Spider drone can be controlled using the Mambo pyparrot module!**

All you have to do is replace the Mambo's bluetooth address in the script with that of the Spider's. If you don't know your Spider's address, you can easily edit the findMambo.py script  to search for "RS_" instead of "Mambo" on [line 37 of the findMambo script](https://github.com/amymcgovern/pyparrot/blob/master/pyparrot/scripts/findMambo.py#L37).

Note that most sensor data available on the Mambo is not accessible from the Spider. I think only battery can be accessed.

---

Hey Amy,
I heard that the Parrot Mambo and Spider share commonalities in their firmware and hardware. Does this library work with the Spider, too?

Thanks for your fantastic work on this project!
Peter

**Comment by amymcgovern** [comment]
I don't have a spider to test.  I'd say try it out and let me know.

**Comment by petercunha** [comment]
Will do :+1:

**Comment by petercunha** [comment]
Update: It works!
