### ISSUE TITLE
Mambo Altitude over BLE?

### ISSUE THREAD

**Issue by petercunha** [amymcgovern/pyparrot#61]
Hello,
Is there any way to acquire the Parrot Mambo's Altitude data over BLE? It doesn't seem like something that should be restricted to WiFi, but I understand there may be hardware limitations.

**Comment by amymcgovern** [comment]
No, parrot current severely limits what they send over BLE.  In my experience with the BLE protocol, the bandwidth is quite limited.

**Comment by petercunha** [comment]
Understood, thanks.
