### ISSUE TITLE
Wifi Connection Error -python newbie 

### ISSUE THREAD

**Issue by machinelearner452** [amymcgovern/pyparrot#62]
I am new to python and parrot mambo programming. I am trying to get this application to work for my wife who is a fifth-grade teacher. 
The issue I am trying to connect parrot mambo via wifi on my window 10 laptops. I have an FPV drone. 
I followed the Installation offered by Dr.  Amy: https://pyparrot.readthedocs.io/en/latest/installation.html#installing-from-pip
I was able to get the drone to take off only twice (no flips nor landing), but now nothing is working?
I confirmed the drone still works via a remote and Bluetooth connection.

The issue seems to be a socket error - Erron 100060 - the third party did not properly respond after a period.

I am able to connect to the mambo wifi network on my laptop.  I am not sure which IP address to use - 92.168.99.3, or the one showing up on the device 192.168.99.32.   I did update the mambo to current firmware.  Also, should the mac address be caps or lower case?
If there is a know safe troubleshooting tool for wifi, or if anyone could offer some suggestions? 
I did a reinstall and still having the issues.  Fixed the pip3 for windows that was causing me to question if I did the installation correctly, the pip shows the install was successful. As my issue remains to get a success wifi connection, may I ask is there a need to have Linux run on the windows machine?  Referencing "findMambo.py"
Thank you

**Comment by amymcgovern** [comment]
I have not seen that socket error before!  As for the IP address, you shouldn't need to be typing that in directly anywhere.  MAC address only matters if you are using BLE.  Since you are on wifi, it is irrelevant.

**Comment by machinelearner452** [comment]
Amy, 
 Thank you for the time to reply. I have not been a success yet, but I believe I am on a path to stop making newbie mistakes and reach a working system.  I am at a point where I just need to create/find the correct script to have the environment to included anaconda3 site-packages, vs just using anaconda2 environments / python 2.  I say this as my current error is cannot find "parrot.mambo module", I can see it in the anacond3 site-package environment and modules in question, it has been clean out of the anacond2 environment.  

Some issues I have addressed so far - learned more about setup.py and the additional commands to have a correct build occur,   Pip vs pip3 advantages when python 2.6 is installed, gotten past the pip 10.0.1 vs 9.x.x issue. based on the learnings I am not sure how the drone in the first place? 

As a small suggestion for your instructions, you may want to suggest readers reference material on "setup.py build" as a prep step, short of this newbie mistake your instruction are super helpful in learning and troubleshooting this project.

If it ok with you, I will close this in about a week, after I have been successful get the project to work.

**Comment by amymcgovern** [comment]
Why did you do the setup.py approach?  Why not just do pip install pyparrot?  That is how I designed it to work and if you are using anaconda, it will install it all in the right site package directories.

**Comment by amymcgovern** [comment]
Also, yeah you definitely have to use python3 and python3's pip (which is pip3)

**Comment by machinelearner452** [comment]
Amy, 
**Thank you again for putting this project together and sharing**! 
After a bunch of clean-up and rework I was able to have the drone reach a flying state using the examples provided. The biggest issue I faced was having anaconda2 and anacond3 installed. I tried all I could figure out to have the project run in just anaconda3, without success. I ended deleting anaconda2 (I had not used it with past projects, so no loss) and that enable the Windows 10, pip installed, FPV drone to be discovered and take flight. Asa side note if you could have a teammate check on the windows pip installing script, when I ran it ( again as a newbie) I did not see where the example files were installed, and had to go to the web and create a local copy.  
Next step is raspberry pip installation. 

Please let me know if I can offer any help in return?  
Regards Joe
