### ISSUE TITLE
I couldn't run find_mambo?

### ISSUE THREAD

**Issue by hsy77101** [amymcgovern/pyparrot#67]
I tried to run find_mambo for scanning Bluetooth Address of Mambo like the follwing.
sudo find_mambo

But I couldn't run find_mambo. There was no command.

I already installed required files by instruction of documents.
And checked documents like the following address.
https://pyparrot.readthedocs.io/en/latest/quickstartmambo.html

Where is find_mambo? 
or Do I need to run like the following?
sudo python findMambo.py

Please let me know that.
Thank you.

**Comment by amymcgovern** [comment]
It should be in your anaconda/bin directory.

**Comment by jduncan8142** [comment]
If you did a git clone in to your home directory (on linux) it is in ~/pyparrot/pyparrot/scripts

**Comment by amymcgovern** [comment]
It is installed in bin if you do pip install

**Comment by hsy77101** [comment]
Thank you. 
But I solved it by other way.
