### ISSUE TITLE
Any support for connection through virtual ethernet interface?

### ISSUE THREAD

**Issue by skicombinator** [amymcgovern/pyparrot#75]
Hi,
I'm trying to use this API with drone simulator, `parrot-sphinx`. 
The simulator provides virtual ethernet interface on host side and drone side. However, I found that there are only Wifi and BLE connection in pyparrot. 
Is there any support for virtual ethernet connection? Please let me know if you have any plan for this.
Thanks.

**Comment by amymcgovern** [comment]
I do not have any current plans for this but getting it to work on the simulator would be useful eventually.
