### ISSUE TITLE
Does ground camera for Mambo support for WiFi connection only?

### ISSUE THREAD

**Issue by sangwoo-joh** [amymcgovern/pyparrot#76]
I know that Mambo without FPV can take pictures with its ground camera, and get those data through BLE.
However, I only found that Mambo ground camera sample, `example/demoMamboGroundCam.py`, only supports WiFi connection.
Is there any plan for supporting BLE connection for communicating ground camera?
Thank you.

**Comment by amymcgovern** [comment]
The BLE interface is not the same as the wifi one and is VERY slow.  It is over 3 seconds to download photos over BLE.
