### ISSUE TITLE
Support for parrot disco

### ISSUE THREAD

**Issue by aanast01** [amymcgovern/pyparrot#78]
Could this be used for the disco? Does anyone know what needs to be changed in order to be able to control the disco through python code?

**Comment by amymcgovern** [comment]
I don't have a disco to test.  One of the contributors @Victor804  has been working to make a swing work.  Perhaps they have a disco and could report if it works.

**Comment by Victor804** [comment]
Hi,
I don't know if the flying behavior of disco is similar to swing.  But I think the commands are similar to the bebop one (except for takeoff) so you can use the bebop code and change some commands.  It's all in ardrone3.xml 😉.
