### ISSUE TITLE
can any one share the files and structure of netifaces for windows 10, python 3.6?

### ISSUE THREAD

**Issue by machinelearner452** [amymcgovern/pyparrot#81]
Hi, 
 Can anyone share the files and file structure of "netifaces" for windows 10, python 3.6.  
I made the mistake of doing a force reinstall and the current pip has issues. 
pip install --upgrade --force-reinstall netifaces
The issue is the netifaces does not display in site-packages.
netifaces is used in zeroconf.py for wifi connections with bebop. 

Thanks in advance for all the help and anything that can be offered on this one.

**Comment by amymcgovern** [comment]
Going to say the the best answer is often a clean install.
