### ISSUE TITLE
Joystick

### ISSUE THREAD

**Issue by Victor804** [amymcgovern/pyparrot#83]
I wanted to know if you were interested in an example code to control a drone with a joystick.

**Comment by machinelearner452** [comment]
Victor804, yes I have an interest.   As a fyi, I am playing with have live keyboard control.

**Comment by amymcgovern** [comment]
Cool.  I am mainly focused on the autonomous programming but I'm always keen on more demos and that would likely make a nice demo program.

**Comment by Victor804** [comment]
I'll work on it to make it easier to use and modify.  Thank you for your answers !
