### ISSUE TITLE
Feature Request - Installation guide for the non-technically literate

### ISSUE THREAD

**Issue by JackdQuinn** [amymcgovern/pyparrot#85]
Hi Amy,

Love the project.  I wrote an implementation guide for the mambo fpv for those less familiar with computers.  I have finished the windows guide (below) and will be working on one for linux soon.
Please use it if you find it useful:

*** Start your download of Visual Studio and include the Visual C++ module
this is required (and free) software for the windows installation

Special Install Python
Special install Python, click add python to path (this will clear up some command line call issues) 

type py to open python3 on windows
(type python3 on linux)

check installation by typing py in the windows cmd line, this should enter python
type: quit()
this should exist python
type:python
this should enter python
type:quit()

(windows) type: pip
this should produce a rather large list of options
***the pip command will not work inside of python

Update pip installation with 
(Windows) python -m pip install -U pip
(Linux/Mac) pip install -U pip
pip install --upgrade pip

Alternatively: download the pip file then run the pip file
in python open the pip file
-- from cmd, cd Desktop, dir, py "pip file name", enter

Use Pip for Installing
in cmd line type: pip install untangle
this will install the "untangle" package

in cmd line type: 
pip install pyparrot

in cmd line type:
pip install zeroconf
****visual studio c++14.0 is a requirement
***This is a large download (3gigs) and should be done beforehand

Connect via wifi
wifi connection
If you are using the wifi (e.g. Mambo FPV), you need to connect your controlling device (laptop, computer, etc) to the wifi for the drone. Look for a wifi network named Mambo_number where number changes for each drone.

After connection to your drone its time to run code !!!!

Run code by cd'ing down to the directory (the folder your python code is in) and running the desired python file from the cmd line
example:
open command line 
type: cd desktop
this will Change your Directory to the desktop
type:dir
this will display a list of all the folders (directories) on the desktop
type: cd yourFolderNameHere
type: dir
this will display all the files and folders in the directory
type: py TheNameOfTheFileYouWantToRun.py
*when you click enter the file will begin to run, if you are using the demo scripts you should see lots of nice feedback as it changes states
**you can use the arrow keys to go through your history of commands which can save you lots of time if your file names are long =)
***if you have several connects and disconnects try restarting your computer or resetting your ip (for the more technically inclined) 
**** if you have crashes where the drone is flipping to one side when it shouldn't check the blades and bumpers.
The bumpers can shift after a crash and prevent the blades from spinning, or slow down their spin, which causes unintended flips

**Comment by amymcgovern** [comment]
Working on a major update today (adding in @Victor804 's parrot swing code) and I'll get this added to the docs also
