### ISSUE TITLE
How to send streaming via network

### ISSUE THREAD

**Issue by ManuelCostanzo** [amymcgovern/pyparrot#88]
Hello, i have a question. I want to send the bebop 1 streaming over network. How can I achieve this using/modifying your library. And, it is possible to reduce/compress the quality of the streaming. 

Thanks a lot

**Comment by Victor804** [comment]
Hi,
I think the commands that will interest you are: 
```
start_video_stream()
stop_video_stream() 
set_video_stream_mode(mode)
```
 You have three different stream modes ("low_latency", "high_reliability", "high_reliability_low_framerate) by default this is low_latency.
 If you want to make changes you go to ./pyparrot/pyparrot/Bebop.py 

I hope that will help you.

**Comment by ManuelCostanzo** [comment]
Hello Victor. Thanks for reply.
Im using these methods but I have a 1.5 / 2 seconds lag. While in the mobile apk does not occur. Can this be solved?

**Comment by Victor804** [comment]
I'm not working on this part so I can't help you sorry. 
But @amymcgovern can certainly help you.
