### ISSUE TITLE
Using Controller plus PyParrot

### ISSUE THREAD

**Issue by rymoore** [amymcgovern/pyparrot#89]
I'm about to kick off a project using the (awesome) PyParrot library, and I'm wondering, is it still possible to somehow control either the Mambo or Bebop2 device with the off the shelf controller while _also_ pulling photos / video using PyParrot from a separate device?

**Comment by amymcgovern** [comment]
I don't think so.  The drone only lets one controller perform a handshake at once, at least in the case of the bebop.  The mambo can actually handle the bluetooth RC *and* a wifi connection to a laptop at the sometime.
