### ISSUE TITLE
Please how to solve "NameError: name 'DefaultDelegate' is not defined" for BLE.

### ISSUE THREAD

**Issue by hsy77101** [amymcgovern/pyparrot#93]
My environment is  Raspberry Pi 3 Model B, preinstalled  python3

I am trying Parrot Mambo with BLE connection.
So I installed all of your mentioned in "https://pyparrot.readthedocs.io".

After then I tried to scan by using following link.
"https://pyparrot.readthedocs.io/en/latest/quickstartminidrone.html"

But I met the following error. I don't know how I solve this error.
Please let me know how to solve it. Thank you.

pi@raspberrypi:~/pyparrot/pyparrot/scripts $ sudo python ./findMinidrone.py
Traceback (most recent call last):
  File "./findMinidrone.py", line 18, in <module>
    class ScanDelegate(DefaultDelegate):
NameError: name 'DefaultDelegate' is not defined

**Comment by amymcgovern** [comment]
Did you install the bluepy package?

**Comment by hsy77101** [comment]
Yes, I did. 
I solved this issue. 
I just run "pi@raspberrypi:~/pyparrot/pyparrot/scripts $ sudo python3 ./findMinidrone.py"
instead of "pi@raspberrypi:~/pyparrot/pyparrot/scripts $ sudo python ./findMinidrone.py".
I just replace "python" to "python3" of command.

I think you need to update document with exact information.
Anyway, Thank you for your comment.

**Comment by amymcgovern** [comment]
Can't exactly write it when people have all different python installations.  You just need to know to run python 3.  But I will update it into the FAQ to ensure people are running python 3 and knowing the python 2 error helps!

**Comment by hsy77101** [comment]
Ok. Dr.Amy. Thank you.
Your pyparrot is great for us.
